[project]
name = "cerebras-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-genai>=1.57.0",
    "requests>=2.32.5",
    "tenacity>=9.1.2",
]
